**an array is a data structure that stores a collection of items, all of the same type, in a contiguous memory block.**

In [1]:
arr1 = ['pune',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [3]:
type(arr1)

list

In [5]:
arr1[0]

'pune'

In [7]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [9]:
type(arr2)

numpy.ndarray

In [11]:
print(arr2)

[10 20 30 40 50]


In [13]:
arr2

array([10, 20, 30, 40, 50])

In [15]:
arr3 = numpy.array((100,200,300,400,500))

In [17]:
type(arr3)

numpy.ndarray

In [19]:
import numpy as np
a0 = np.array(10)

In [21]:
print(a0)

10


In [23]:
a0.ndim

0

In [25]:
a0

array(10)

In [27]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [29]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
a1.ndim


1

In [33]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [35]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [37]:
a2.ndim

2

In [39]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [41]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [43]:
a3.ndim

3

In [45]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [47]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [49]:
a4.ndim

4

In [51]:
amix1 = np.array(['pune',1,"mumbai",2])

In [53]:
amix1

array(['pune', '1', 'mumbai', '2'], dtype='<U11')

In [55]:
type(amix1)

numpy.ndarray

In [57]:
amix2 = np.array([True,5])

In [61]:
amix2

array([1, 5])

In [63]:
amix3 = np.array([False,10])

In [65]:
amix3

array([ 0, 10])

In [67]:
amix4 = np.array([True,'shridhar',5,5.0])

In [69]:
amix4

array(['True', 'shridhar', '5', '5.0'], dtype='<U32')

In [71]:
amix6 = np.array([False,10],dtype = np.int32)

In [75]:
amix6

array([ 0, 10])

In [77]:
amix7 = np.array([1,5.55,2,6.9], dtype = np.float64)

In [79]:
amix7

array([1.  , 5.55, 2.  , 6.9 ])

In [81]:
arr1[0] 

'pune'

In [85]:
arr2[1]  

20

In [87]:
arr2[0]+arr2[1]

30

In [89]:
a2[1,2]

30

In [91]:
a2[2,2]

300

In [93]:
a3[0,0,0]

1

In [95]:
a3[0,0,1]

2

In [97]:
a3[0,0,2]

3

In [99]:
a3[0,1,0]

10

In [101]:
a3[0,1,1]

20

In [103]:
a3[0,1,2]

30

In [105]:
a3[1,0,0]

100

In [107]:
a4[0,0,0,0]

4

In [109]:
a4[0,0,0,1]

44

In [111]:
a4[0,0,0,2]

444

In [113]:
a4[0,0,0,3]

4444

In [115]:
a4[0,0,1,0]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [117]:
a12 = np.array([1,2,3])

In [121]:
a12[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [125]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [127]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [129]:
arr2

array([10, 20, 30, 40, 50])

In [131]:
arr2[-1]

50

In [133]:
arr2[-2]

40

In [135]:
arr2[1:]

array([20, 30, 40, 50])

In [137]:
arr2[:3]

array([10, 20, 30])

In [139]:
arr2[:]

array([10, 20, 30, 40, 50])

In [141]:
arr2[1:4:1]

array([20, 30, 40])

In [143]:
arr2[1:4:2]

array([20, 40])

In [145]:
arr2[:4:3]

array([10, 40])

In [147]:
arr2[::4]

array([10, 50])

In [149]:
arr2[::]

array([10, 20, 30, 40, 50])

In [151]:
for i in arr2:
  print(i)

10
20
30
40
50


In [153]:
x = np.where(arr2 == 20)
print(x)

(array([1], dtype=int64),)


In [155]:
x = np.where(arr2 == 50)
print(x)

(array([4], dtype=int64),)


In [157]:
x = np.where(arrr == 2)
print(x)

(array([1, 4, 7], dtype=int64),)


In [159]:
arraysort = np.array([2,1,5,3,7,5,9,8,5,7,3])

In [161]:
np.sort(arraysort)

array([1, 2, 3, 3, 5, 5, 5, 7, 7, 8, 9])

In [163]:
np.insert(arr2,5,60)

array([10, 20, 30, 40, 50, 60])

In [165]:
np.insert(arraysort,11,10)

array([ 2,  1,  5,  3,  7,  5,  9,  8,  5,  7,  3, 10])

In [167]:
np.insert(arraysort,0,100)

array([100,   2,   1,   5,   3,   7,   5,   9,   8,   5,   7,   3])

In [169]:
np.delete(arraysort,0)

array([1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [171]:
arraysort

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [173]:
arrr1 = np.insert(arr2,5,60)

In [175]:
arrr1

array([10, 20, 30, 40, 50, 60])

In [177]:
arr2

array([10, 20, 30, 40, 50])

In [179]:
index = [0,1,2]

In [181]:
arrr2 = np.delete(arr2,index)

In [183]:
arrr2

array([40, 50])

In [185]:
arr2

array([10, 20, 30, 40, 50])

In [187]:
np.flip(arr2)

array([50, 40, 30, 20, 10])

In [189]:
arr2

array([10, 20, 30, 40, 50])

In [191]:
arrflip = np.flip(arr2)

In [193]:
arrflip

array([50, 40, 30, 20, 10])

In [195]:
arr2[0] = 100

In [197]:
arr2

array([100,  20,  30,  40,  50])

In [199]:
arr2.sort()

In [201]:
arr2

array([ 20,  30,  40,  50, 100])

In [203]:
np.append(arr2,1000)

array([  20,   30,   40,   50,  100, 1000])

In [205]:
arr2

array([ 20,  30,  40,  50, 100])

In [207]:
arr2.append(1000)

AttributeError: 'numpy.ndarray' object has no attribute 'append'